# hash:sha256:d0428211a8039fa597dc9d8890f4938a12a0a70d548dfce72c9f94288bd05a97
FROM registry.acmecorp-demo.codeocean.com/codeocean/miniconda3:4.12.0

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /
